apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    env: test
  name: webcolor
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
    nodePort: 30100
  selector:
    env: test
  type: NodePort
status:
  loadBalancer: {}
