apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webcolor
  name: webcolor
spec:
  containers:
  - image: 24031990/webcolor:latest
    name: webcolor
    resources: {}
  nodeName: worker1 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
