# start from base
FROM ubuntu:18.04

LABEL maintainer="Annamalai <annamalaipon@gmail.com>"

RUN apt-get update -y && \
    apt-get install -y python-pip python-dev

# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt
WORKDIR /app

RUN pip install -r requirements.txt

ENV MYSQL_DATABASE_USER=root
ENV MYSQL_DATABASE_PASSWORD=root
ENV MYSQL_DATABASE_DB=EmployeeDB
ENV MYSQL_DATABASE_HOST=mysql

COPY . /app

CMD [ "python", "./app.py" ]
